let suggestions = [
    "SPACIFY",
    "Tech Ice",
    "Crazy Tech Genius",
    "Our Sun SPACIFY",
    "Planet Mercury SPACIFY",
    "Planet Venus SPACIFY",
    "Planet Earth SPACIFY",
    "Planet Mars SPACIFY",
    "Planet Jupiter SPACIFY",
    "Planet Saturn SPACIFY",
    "Planet Uranus SPACIFY",
    "spacify.netlify.app",
    "SPACIFY Homepage",
    "Planet Neptune SPACIFY",
    "youtube.com",
]